#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Ensure correct version of node is used for hooks - supports nvm and nvs
export NVM_DIR="$HOME/.nvm"
if [ -z "${NVS_HOME}" ]; then
	export NVS_HOME=$(command -v nvs 2>/dev/null | sed 's/nvs.nvs/nvs/g')
fi
# export NVS_HOME=$(command -v nvs 2>/dev/null | sed 's/nvs.nvs/nvs/g')
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use
[ -s "$NVS_HOME/nvs.sh" ] && . "$NVS_HOME/nvs.sh" && echo "using nvs" && nvs use

# Run audit/type-check/etc.
npm run check-audit && npm run type-check && npm run test
